### ISSUE TITLE
RangeError [ERR_INDEX_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by abdulrahman-khankan** [image-size/image-size#106]
```
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1015:11)
    at Buffer.readUInt16LE (buffer.js:1063:5)
    at Object.isCUR [as detect] (/some_directory/node_modules/image-size/lib/types/cur.js:7:14)
    at module.exports (/some_directory/node_modules/image-size/lib/detector.js:8:33)
    at lookup (/some_directory/node_modules/image-size/lib/index.js:22:14)
    at module.exports (/some_directory/node_modules/image-size/lib/index.js:96:12)
    at exports.default (/some_directory/src/downloadImage.js:72:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

Hi, I have a batch job where I fetch the size of 20k images, and I found this in the logs about 10 times. Could this exception be related to `image-size` package? Or do you believe it's more likely that something wrong with the image at the time?

Thanks.

**Comment by netroy** [comment]
@abdulrahman-khankan looks like you might have some bad images in the batch.
The error occurs when the [library tries to read the first 2 bytes](https://github.com/image-size/image-size/blob/master/lib/types/cur.js#L7) for these images.
If you debug, & find this to be an issue with the library instead, please feel free to comment here. 
I'll close the issue.
