### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by PizzaPartyInc** [image-size/image-size#198]
Hi,

I'm getting an error when trying to get dimensions of a specific image. 

Version: 0.7.4

Stack trace: 
`RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
at boundsError (internal/buffer.js:71:11)
at Buffer.readUInt16LE (internal/buffer.js:230:5)
at readUInt (C:\PathToProject\node_modules\image-size\lib\readUInt.js:8:17)
at extractOrientation (C:\PathToProject\node_modules\image-size\lib\types\jpg.js:74:21)
at validateExifBlock (C:\PathToProject\node_modules\image-size\lib\types\jpg.js:49:12)
at Object.calculate (C:\PathToProject\node_modules\image-size\lib\types\jpg.js:118:21)
at lookup (C:\Projects\PathToProject\node_modules\image-size\lib\index.js:26:35)
at module.exports (C:\PathToProject\node_modules\image-size\lib\index.js:122:12)`

Usage
`import * as sizeOf from 'image-size';
const dimensions = sizeOf(image.path);
`

Image in question is attached. Somehow I have doubts that this image is corrupted, since I was able to get its dimensions with c# code without problems. Also tried async examples from documentation with same results. 

Anything I missed? :)

![darkknight](https://user-images.githubusercontent.com/37663061/63351386-cd9a4c80-c367-11e9-8cf6-2771665b166f.jpg)

**Comment by beliayeu** [comment]
the same issue is on my side
per my understanding that is a known issue https://github.com/image-size/image-size/issues/94
as a workaround an alternative library like probe-image-size can be taken

**Comment by mnpenner** [comment]
Yep. Getting this too:

```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:71:11)
    at Buffer.readUInt16LE (internal/buffer.js:230:5)
    at Object.isCUR [as detect] (/mnt/c/Users/Mark/PhpstormProjects/imagegather/node_modules/image-size/lib/types/cur.js:7:14)
    at module.exports (/mnt/c/Users/Mark/PhpstormProjects/imagegather/node_modules/image-size/lib/detector.js:8:33)
    at lookup (/mnt/c/Users/Mark/PhpstormProjects/imagegather/node_modules/image-size/lib/index.js:22:14)
    at module.exports (/mnt/c/Users/Mark/PhpstormProjects/imagegather/node_modules/image-size/lib/index.js:96:12)
    at main (/mnt/c/Users/Mark/PhpstormProjects/imagegather/src/index.ts:73:38)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by netroy** [comment]
@PizzaPartyInc the issue you are facing, has been fixed. it's released as `v0.7.5`

**Comment by netroy** [comment]
@beliayeu the proposal to switch to streams is to fix a completely different issue around large JPEGs. If you got a `ERR_BUFFER_OUT_OF_BOUNDS` error, can you please share with the entire stacktrace, & the image (if possible)

**Comment by netroy** [comment]
@mnpenner from the stacktrace you posted, it sounds like that the image in question was invalid.
would it be possible to share the image with me?
