### ISSUE TITLE
Node 10 compatibility

### ISSUE THREAD

**Issue by arovetto** [image-size/image-size#412]
I see that starting with version 1.1.0 the library is not anymore compatible with node.js 10. 
I get the following error trying to start an application using image-size:

D:\bitbucket\ir-rt-reitek-livechat\node_modules\image-size\dist\index.js:36
                size.type = size.type ?? type;
                                       ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\bitbucket\ir-rt-reitek-livechat\node_modules\image-thumbnail\src\index.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\bitbucket\ir-rt-reitek-livechat\node_modules\image-thumbnail\index.js:3:18)

It's very appreciated if the compatibility with node.js is preserved.

Thanks a lot

**Comment by netroy** [comment]
Nodejs 10 went end-of-life in early 2021. I really don't want to provide support for decommissioned versions of nodejs.

If you need HEIF/HEIC support, my recommendation is to upgrade to a maintained version of nodejs.

But if you are not able to upgrade nodejs, please fix the dependency version to `1.0.3`.
