### ISSUE TITLE
Corrupt JPG, exceeded buffer limits on 0.6.0 version

### ISSUE THREAD

**Issue by dxcqcv** [image-size/image-size#93]
When I uploaded specify image I got this error on 0.6.0 version, [image like this](https://www.dropbox.com/s/jwmwmi7trlagv8x/dsf.jpg?dl=0)

the error info is

```
TypeError: Corrupt JPG, exceeded buffer limits
    at validateBuffer (D:\dev\github\auto-pages\node_modules\image-size\lib\types\jpg.js:23:11)
    at Object.calculate (D:\dev\github\auto-pages\node_modules\image-size\lib\types\jpg.js:42:5)
    at lookup (D:\dev\github\auto-pages\node_modules\image-size\lib\index.js:26:31)
    at module.exports (D:\dev\github\auto-pages\node_modules\image-size\lib\index.js:101:12)
    at app.post (D:\dev\github\auto-pages\build\dev-server.js:151:20)
    at Layer.handle [as handle_request] (D:\dev\github\auto-pages\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\dev\github\auto-pages\node_modules\express\lib\router\route.js:137:13)
    at Immediate.<anonymous> (D:\dev\github\auto-pages\node_modules\multer\lib\make-middleware.js:53:37)
    at runCallback (timers.js:655:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by netroy** [comment]
I have bumped up the buffer size in 0.6.1.. that sorta fixes the issue.
