### ISSUE TITLE
TypeError: Corrupt JPG, exceeded buffer limits

### ISSUE THREAD

**Issue by stone12379** [image-size/image-size#96]
Maybe that's because the JPG is too big, but I would like to know how to avoid.
http://pan.baidu.com/s/1geSFOFT

**Comment by stephen-last** [comment]
I have the same issue:

> TypeError: Corrupt JPG, exceeded buffer limits
> at validateBuffer (C:\...\node_modules\image-size\lib\types\jpg.js:23:11)
> at Object.calculate (C:\...\node_modules\image-size\lib\types\jpg.js:42:5)
> at lookup (C:\...\node_modules\image-size\lib\index.js:26:31)
> at C:\...\node_modules\image-size\lib\index.js:93:22
> at C:\...\node_modules\image-size\lib\index.js:50:9
> at C:\...\node_modules\graceful-fs\graceful-fs.js:43:10

I need to be able to work with large images.

How can I increase the buffer limits..?

**Comment by onlytropics** [comment]
I just encountered it, too. I can give you an example image, if needed. In my case the image is 2362x2362 pixels, so not too big really, and can be read just fine by any image editor I have.

**Comment by alexahdp** [comment]
Is there any decision for this problem?

**Comment by mmoczulski** [comment]
Luckily, I found an easy workaround for that problem. Instead of putting the file path to the function, put buffer with already loaded file.

For instance:

```
fs.readFile(filePath, (err, buf) => {
  if (err) ...
  const result = sizeOf(buf);
  console.log(`dim: ${result.width} x ${result.height}`);
});
```

**Comment by johsmic** [comment]
I get this error when the jpg-image uses CMYK color model.

**Comment by AndrewKvalheim** [comment]
Is this the same as #34?
