### ISSUE TITLE
is image URL with HTTPS supported?

### ISSUE THREAD

**Issue by sonyarianto** [image-size/image-size#97]
I got this when try to detect image size URL with https
```
_http_client.js:129
    throw new Error('Protocol "' + protocol + '" not supported. ' +
    ^

Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:129:11)
    at request (http.js:39:10)
    at Object.get (http.js:43:13)
    at Object.<anonymous> (/root/2.js:9:6)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
```

**Comment by netroy** [comment]
@sonyarianto if you are using [the example from the readme](https://github.com/image-size/image-size#using-a-url), please change `var http = require('http')` to `var https = require('https')` instead.

alternatively you can [parse the url with `url.parse`](https://nodejs.org/docs/latest/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost), & pick between `http` & `https` based on the value of `protocol` of the parsed url.

**Comment by sonyarianto** [comment]
@netroy thanks and better mention it on the readme as well :)
